apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-app:latest  # Replace with your actual image
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "mongodb://mongodb:27017/mydatabase"  # Change as needed
