apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-app:latest  # Replace with your actual image
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend:5000"  # Adjust according to your setup
